# config.yaml
test:
    trainer:
        max_epochs: 1
        accelerator: gpu
        devices: [ 0 ]
    data:
        params:
            data_type: hpatches
            batch_size: 1
            num_workers: 1
            hpatches_params:
                type: hpatches
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/HPatch
                alteration: i
                image_size: 512
                gray: False
            euroc_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/EuRoC
                gray: True
            kitti_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/KITTI
                gray: True
            megadepth_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/Dataset/disk-data/megadepth
                using_cache: True
                pairs_per_scene: 100
                image_size: 512
                colorjit: True
                gray: True
                crop_or_scale: 'scale'
            uma_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/KITTI
                gray: True
    model:
        params:
            model_type: Alike
            task_type: VisualizeTrackingError
            Alike_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/alike-t.pth
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: True
            KeyNet_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/keynet_pytorch.pth
                num_filters: 8
                num_levels: 3
                kernel_size: 5
            SuperPoint_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/superpoint_v1.pth
            GoodPoint_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/goodpoint.pth
                c0: 3
                c1: 8
                h0: 4
            Harris_params:
                block_size: 5
                ksize: 3
                k: 0.04
            extractor_params:
                nms_dist: 4
                min_score: 0.0
                top_k: 500
                threshold: 0
                border_dist: 8
            matcher_params:
                type: optical_flow
                optical_flow_params:
                    distance: 10
                    win_size: 15
                    levels: 3
                    interation: 40
                    gray: False
            VisualizeTrackingError_params:
                save_path: /home/server/linyicheng/py_proj/keypoint_bench/tracking_error.png
                output: /home/server/linyicheng/py_proj/keypoint_bench/output/
                image:
                    radius: 12
                    max_error: 5
                    color: 255,0,0
            repeatability_params:
                save_path: /home/server/linyicheng/py_proj/keypoint_bench/harris.png
                output: /home/server/linyicheng/py_proj/keypoint_bench/output/
                th: 3
                image:
                    radius: 6
                    max_error: 5
                    color: 255,0,0
