test:
  data:
    params:
      batch_size: 1
      data_type: hpatches
      hpatches_params:
        alteration: v
        gray: false
        image_size: 512
        root: /home/data/WangShuo/datasets/HPatch
        type: hpatches
      num_workers: 1
  model:
    params:
      model_type: XFeat
      task_type: repeatability
      extractor_params:
        border_dist: 8
        min_score: 0.0
        nms_dist: 6
        threshold: 0
        top_k: 1000
      matcher_params:
        type: brute_force
        optical_flow_params:
            distance: 10
            win_size: 21
            levels: 3
            interation: 40
            gray: False
      repeatability_params:
        image:
          color: 255,0,0
          max_error: 3
          radius: 6
        output: /home/output/
        save_path: /home/output/alike_v.png
        th: 3
      Alike_params:
        c1: 8
        c2: 16
        c3: 32
        c4: 64
        dim: 64
        single_head: true
        weight: /home/code/keypoint_bench/weights/alike-t.pth
      D2Net_params:
        weight: /home/code/keypoint_bench/weights/d2_tf.pth
      DISK_params:
        weight: /home/code/keypoint_bench/weights/disk.pth
      EdgePoint_params:
        c1: 8
        c2: 16
        c3: 32
        c4: 64
        dim: 64
        single_head: true
        weight: /home/code/keypoint_bench/weights/EdgePoint.pt
      GoodPoint_params:
        c0: 3
        c1: 8
        h0: 4
        weight: /home/code/keypoint_bench/weights/goodpoint.pth
      Harris_params:
        block_size: 5
        k: 0.04
        ksize: 3
      KeyNet_params:
        kernel_size: 5
        num_filters: 8
        num_levels: 3
        weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/keynet_pytorch.pth
      LETNet_params:
        weight: /home/code/keypoint_bench/weights/letnet.pth
      SuperPoint_params:
        weight: /home/code/keypoint_bench/weights/superpoint_v1.pth
      XFeat_params:
        weight: /home/code/keypoint_bench/weights/xfeat.pt
      r2d2_params:
        weight: /home/code/keypoint_bench/weights/r2d2_WASF_N16.pt
      sfd2_params:
        weight: /home/code/keypoint_bench/weights/sfd2.pth
  trainer:
    accelerator: gpu
    devices:
    - 1
    max_epochs: 1
