# config.yaml
test:
    trainer:
        max_epochs: 1
        accelerator: gpu
        devices: [ 0 ]
    data:
        params:
            data_type: megadepth
            batch_size: 1
            num_workers: 4
            megadepth_params:
                type: megadepth
                root: /home/data/Dataset/disk-data/imw2020-val
                using_cache: True
                pairs_per_scene: 100
                image_size: 512
                colorjit: True
                gray: False
                crop_or_scale: 'scale'
    model:
        params:
            model_type: Alike
            task_type: AUC
            Alike_params:
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: true
                weight: /home/code/keypoint_bench/weights/alike-t.pth
            D2Net_params:
                weight: /home/code/keypoint_bench/weights/d2_tf.pth
            DISK_params:
                weight: /home/code/keypoint_bench/weights/disk.pth
            EdgePoint_params:
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: true
                weight: /home/code/keypoint_bench/weights/EdgePoint.pt
            GoodPoint_params:
                c0: 3
                c1: 8
                h0: 4
                weight: /home/code/keypoint_bench/weights/goodpoint.pth
            Harris_params:
                block_size: 5
                k: 0.04
                ksize: 3
            KeyNet_params:
                kernel_size: 5
                num_filters: 8
                num_levels: 3
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/keynet_pytorch.pth
            LETNet_params:
                weight: /home/code/keypoint_bench/weights/letnet.pth
            SuperPoint_params:
                weight: /home/code/keypoint_bench/weights/superpoint_v1.pth
            XFeat_params:
                weight: /home/code/keypoint_bench/weights/xfeat.pt
            r2d2_params:
                weight: /home/code/keypoint_bench/weights/r2d2_WASF_N16.pt
            sfd2_params:
                weight: /home/code/keypoint_bench/weights/sfd2.pth
            extractor_params:
                nms_dist: 4
                min_score: 0.0
                top_k: 2000
                threshold: 0
                border_dist: 8
            matcher_params:
                type: brute_force
                optical_flow_params:
                    distance: 10
                    win_size: 21
                    levels: 3
                    interation: 40
                    gray: False
                brute_force_params:
                    metric: euclidean
                    max_distance: 5
                    cross_check: True
            AUC_params:
                th: [ 5, 10, 20 ]
                output: /home/output/

