# config.yaml
test:
    data:
        params:
            datatype: hpatches
            batch_size: 1
            num_workers: 8
            hpatches_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/HPatch
                alteration: v
                image_size: 512
                gray: False
            euroc_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/EuRoC
                gray: True
            kitti_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/KITTI
                gray: True
            megadepth_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/Dataset/disk-data/megadepth
                using_cache: True
                pairs_per_scene: 100
                image_size: 512
                colorjit: True
                gray: False
                crop_or_scale: 'scale'
            uma_params:
                root: /media/server/4cda377d-28db-4424-921c-6a1e0545ceeb/WangShuo/datasets/KITTI
                gray: True
    model:
        params:
            modeltype: Alike
            pretrained: True
            weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/alike-t.pth
            extractor_params:
                nms_dist: 4
                min_score: 0.0
                top_k: 300
                threshold: 3
            matcher_params:
                type: optical_flow
                visualize: True
                visualize_type: 'key_points_error'
            task_params:
                type: None
