# config.yaml
test:
    trainer:
        max_epochs: 1
        accelerator: gpu
        devices: [ 1 ]
    data:
        params:
            data_type: hpatches
            batch_size: 1
            num_workers: 1
            hpatches_params:
                type: hpatches
                root: /home/data/WangShuo/datasets/HPatch
                alteration: v
                image_size: 512
                gray: False
    model:
        params:
            model_type: Alike
            task_type: MHA
            MHA_params:
                th: [3, 5, 7]
            Alike_params:
                weight: /home/code/keypoint_bench/weights/alike-t.pth
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: True
            KeyNet_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/keynet_pytorch.pth
                num_filters: 8
                num_levels: 3
                kernel_size: 5
            SuperPoint_params:
                weight: /home/code/keypoint_bench/weights/superpoint_v1.pth
            XFeat_params:
                weight: /home/code/keypoint_bench/weights/xfeat.pt
            EdgePoint_params:
                weight: /home/code/keypoint_bench/weights/EdgePoint.pt
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: True
            D2Net_params:
                weight: /home/code/keypoint_bench/weights/d2_tf.pth
            DISK_params:
                weight: /home/code/keypoint_bench/weights/disk.pth
            r2d2_params:
                weight: /home/code/keypoint_bench/weights/r2d2_WASF_N16.pt
            sfd2_params:
                weight: /home/code/keypoint_bench/weights/sfd2.pth
            LETNet_params:
                weight: /home/code/keypoint_bench/weights/letnet.pth
            GoodPoint_params:
                weight: /home/code/keypoint_bench/weights/goodpoint.pth
                c0: 3
                c1: 8
                h0: 4
            Harris_params:
                block_size: 5
                ksize: 3
                k: 0.04
            extractor_params:
                nms_dist: 6
                min_score: 0.0
                top_k: 1000
                threshold: 0
                border_dist: 8
            matcher_params:
                type: brute_force
                optical_flow_params:
                    distance: 10
                    win_size: 21
                    levels: 3
                    interation: 40
                    gray: False
                brute_force_params:
                    metric: euclidean
                    max_distance: 5
                    cross_check: True