# config.yaml
test:
    trainer:
        max_epochs: 1
        accelerator: gpu
        devices: [ 1 ]
    data:
        params:
            data_type: tartanair
            batch_size: 1
            num_workers: 1
            tartanair_params:
                type: tartanair
                root: /home/data/Dataset/tartanair/mono/tartanair-test-mono-release/mono/MH001/
                gt: /home/data/Dataset/tartanair/tartanair_cvpr_gt/mono_gt/MH001.txt
                gray: False
    model:
        params:
            model_type: LETNet
            task_type: FundamentalMatrix
            Alike_params:
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: true
                weight: /home/code/keypoint_bench/weights/alike-t.pth
            D2Net_params:
                weight: /home/code/keypoint_bench/weights/d2_tf.pth
            DISK_params:
                weight: /home/code/keypoint_bench/weights/disk.pth
            EdgePoint_params:
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: true
                weight: /home/code/keypoint_bench/weights/EdgePoint.pt
            GoodPoint_params:
                c0: 3
                c1: 8
                h0: 4
                weight: /home/code/keypoint_bench/weights/goodpoint.pth
            Harris_params:
                block_size: 5
                k: 0.04
                ksize: 3
            LETNet_params:
                weight: /home/code/keypoint_bench/weights/letnet.pth
            SuperPoint_params:
                weight: /home/code/keypoint_bench/weights/superpoint_v1.pth
            XFeat_params:
                weight: /home/code/keypoint_bench/weights/xfeat.pt
            r2d2_params:
                weight: /home/code/keypoint_bench/weights/r2d2_WASF_N16.pt
            sfd2_params:
                weight: /home/code/keypoint_bench/weights/sfd2.pth
            extractor_params:
                nms_dist: 6
                min_score: 0.0
                top_k: 1000
                threshold: 0
                border_dist: 8
            matcher_params:
                type: optical_flow
                brute_force_params:
                    metric: euclidean
                    max_distance: 5
                    cross_check: True
                optical_flow_params:
                    distance: 10
                    win_size: 21
                    levels: 3
                    interation: 40
                    gray: False
                light_glue_params:
                    weight: /home/code/keypoint_bench/
            FundamentalMatrix_params:
                save_path: /home/output/fund_e_0.png
                output: /home/output/
                th: 3
