# config.yaml
test:
    trainer:
        max_epochs: 1
        accelerator: gpu
        devices: [ 0 ]
    data:
        params:
            data_type: image_pair
            batch_size: 1
            num_workers: 1
            image_pair_params:
                type: image_pair
                root: /media/ddc_robot/4cda377d-28db-4424-921c-6a1e0545ceeb/Dataset/long_term_image/file.txt
                image_size: 512
                gray: False
    model:
        params:
            model_type: DISK
            task_type: FundamentalMatrixRansac
            Alike_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/alike-t.pth
                c1: 8
                c2: 16
                c3: 32
                c4: 64
                dim: 64
                single_head: True
            KeyNet_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/keynet_pytorch.pth
                num_filters: 8
                num_levels: 3
                kernel_size: 5
            SuperPoint_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/superpoint_v1.pth
            GoodPoint_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/goodpoint.pth
                c0: 3
                c1: 8
                h0: 4
            D2Net_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/d2_tf.pth
            XFeat_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/xfeat.pt
            r2d2_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/sync/weights/r2d2_WASF_N16.pt
            sfd2_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/sync/weights/sfd2.pth
            DISK_params:
                weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/weights/disk.pth
            Harris_params:
                block_size: 5
                ksize: 3
                k: 0.04
            extractor_params:
                nms_dist: 16
                min_score: 0.0
                top_k: 500
                threshold: 0
                border_dist: 8
                save_result: True
            matcher_params:
                type: light_glue
                save_result: True
                brute_force_params:
                    metric: euclidean
                    max_distance: 5
                    cross_check: True
                light_glue_params:
                    weight: /home/server/linyicheng/py_proj/keypoint_bench/keypoint_bench/sync/

            FundamentalMatrixRansac:
                save_path: /home/server/linyicheng/py_proj/keypoint_bench/fund/good_e_0.png
                output: /home/server/linyicheng/py_proj/keypoint_bench/output/
                th: 3


